version: '3.4'

services:
  postgresql:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./env/postgres.env
    restart: always
    networks:
      matrix_network:
        aliases:
          - postgresql
        ipv4_address: 172.50.4.3

  coturn:
    build:
      context: ./build/coturn
      network: host
    image: myy/coturn:latest
    restart: always
    volumes:
      - ./data/coturn/turnserver.conf:/etc/turnserver.conf:ro
      # If you plan to use SSL with STUN, uncomment those two lines
      # And then edit data/coturn/turnserver.conf TOO !
      #- ./data/ssl/privkey.pem:/etc/ssl/private/privkey.pem:ro
      #- ./data/ssl/cert.pem:/etc/ssl/certs/cert.pem:ro
      - ./data/coturn/db:/usr/local/var/db/
    networks:
      matrix_network:
        ipv4_address: 172.50.4.20
        ipv6_address: fc00::115

  matrix:
    image: myy/synapse:latest-intel
    build:
      context: ./build/synapse
      network: host
    volumes:
      - ./matrix/conf:/etc/synapse
      - ./matrix/data:/data
    env_file:
      - ./env/postgres.env # Reuse the PostgreSQL configuration
    environment:
      - SYNAPSE_SERVER_NAME=NameOfYourMatrixServer
      - SYNAPSE_SERVER_ADDRESS=https://matrix.yourdomain.com
      - SYNAPSE_REPORT_STATS=yes # Can be set to "no"
      - SYNAPSE_DATABASE_BACKEND=postgresql # The backend name : postgresql or sqlite
      - SYNAPSE_POSTGRES_DBADDR=postgresql # The network alias we provided to our postgresql server
      # PostgreSQL configuration is inherited from the postgres.env env_file
      - SYNAPSE_VOIP_TURN_MAIN_URL=turn:turn.yourdomain.com:3478?transport=udp
      - SYNAPSE_VOIP_TURN_USERNAME=turn_username
      - SYNAPSE_VOIP_TURN_PASSWORD=turn_password

    networks:
      matrix_network:
        ipv4_address: 172.50.4.2
        ipv6_address: fc00::110
    depends_on:
      - postgresql # For the data
      - coturn     # For the VOIP
    restart: always

volumes:
  pgdata:

networks:
  frontend:
    ipam:
      driver: default
      config:
        - subnet: "172.50.3.0/24"
        - subnet: "fc00::100/124"

  matrix_network:
    ipam:
      driver: default
      config:
        - subnet: "172.50.4.0/24"
        - subnet: "fc00::110/124" 
